env:
    credentials: "ENCRYPTED[fe4d1be7daa0cdf08f02cadb32a6bd6e35534befb09069328fb2bcd7e2742ccfcd261bc7a9ab9ef8ac25f91b26b1e1d3]"
    rcloneconfig: "ENCRYPTED[b440ef7052bf6e41d5d2ecc1cd52cb61c7d239d408ab775185f00162824b8c6dcd59c438d655f33c306c1d670df554f3]"
    tokentl: "ENCRYPTED[317cd6ee0bbf667687c38fc2fbd575a4a334580b538e9df2e367e34bdef0554864ab76e307e3019a6d1aa1b5ae691dff]"
    idtl: "ENCRYPTED[698e1be9dd591db191e8975b72264a85173fe850b81022d399592102aa99d387d7dcdfa5fb9517ae91826e492176058e]"
    lunch: lunch qassa_X00T-userdebug
    make: mka qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "paiskomom"
       - git config --global user.email "midooneteam@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy knjt:komom/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="🔄 Start sync Source. . ."
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q
      - git clone --depth 1 https://github.com/texascake/local_manifest.git -b qassa .repo/local_manifests
      - sudo apt-get update && sudo apt-get install -y git-lfs && git lfs install
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - repo forall -c 'git lfs install && git lfs pull && git lfs checkout'
      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="komom"
      - export BUILD_USER="komom"
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="🛠️ Boeild komom Started! https://cirrus-ci.com/build/$CIRRUS_BUILD_ID"
      - ./collect.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Boeild $(cd ~/rom/out/target/product/X00T/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="📮 Compressing ccache...."
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="📤 Uploading ccache...."
      - rclone copy ccache.tar.gz knjt:komom -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ ccache Uploaded Successfully!"
